field.formatter.settings.context_links:
  type: mapping
  label: 'Context links'
  mapping:
    partner:
      type: string
      label: 'Partner'
    summary:
      type: boolean
      label: 'Summary or trimmed'
    trim_length:
      type: integer
      label: 'Trim length'
